#if !canImport(ObjectiveC)
import XCTest

extension ApiErrorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ApiErrorTests = [
        ("testDecodeErrorRes", testDecodeErrorRes),
    ]
}

extension DataExporterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DataExporterTests = [
        ("testExportCSV", testExportCSV),
        ("testExportJSON", testExportJSON),
    ]
}

extension STSIntradayTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__STSIntradayTests = [
        ("testDecode30minsInterval", testDecode30minsInterval),
        ("testDecode5minsInterval", testDecode5minsInterval),
    ]
}

extension StockTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StockTests = [
        ("testFetchStockIntraday", testFetchStockIntraday),
        ("testFetchStockIntradayFail", testFetchStockIntradayFail),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ApiErrorTests.__allTests__ApiErrorTests),
        testCase(DataExporterTests.__allTests__DataExporterTests),
        testCase(STSIntradayTests.__allTests__STSIntradayTests),
        testCase(StockTests.__allTests__StockTests),
    ]
}
#endif
